server:
  port: 9080

logging:
  level:
    org.springframework: ERROR
    ru.raskopova: DEBUG
  pattern:
    console: "[%-5level] %d{HH:mm:ss.SSS} g:%X{guid} o:%X{oper} [%-26logger{26}:%L]: %m%wEx%n"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BookShop
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate.ddl-auto: none
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'
config:
  security:
    secret: "GJDUWE9REC"
